const main = async () => {};

main().then(console.log).catch(console.error);
